---
title: "mixOmics 6.2.0"
author: "F.Rohart"
date: "17 July 2017"
output: pdf_document
---
```{r global_options, include=TRUE,echo=FALSE}
rm(list=ls())
#setwd("~/Work/git/package-mixOmicsv6")

# knitr::opts_chunk$set(#fig.width=4, fig.height=4, 
#                       dpi=300,
#                       echo=FALSE, warning=FALSE, message=FALSE, fig.align='center')

# if you want to change the size of figures
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE, fig.path= 'Figures/', fig.width=9, fig.height=6)

library(mixOmics)
sourceDir <- function(path, trace = TRUE, ...) {
  for (nm in list.files(path, pattern = "\\.[RrSsQq]$")) {
    if(trace) cat(nm,":")
    source(file.path(path, nm), ...)
    if(trace) cat("\n")
  }
}

library(knitr)
#sourceDir("/Users/florian/Work/git/package-mixOmics/mixOmics/R/",trace=FALSE)
```

This go through all the scripts in "running_scripts/" and outputs graphics and errors, if any. 


```{r,fig.width=8.5, fig.height=7}
library(mixOmics)
#library(ellipse)
#library(rgl)
#source("mixOmicsv6/R/selectVar.R")
#source("mixOmicsv6/R/ipca.R")

additional.test=TRUE

#source("running_scripts//test_plotContrib.R")

scripts.files=list.files("running_scripts/")
scripts.files=scripts.files[grep(".R",scripts.files)]#[1:15]#[c(3,4,5,8,15,16,17,20,22)]
scripts.files

out=lapply(1:length(scripts.files),function(x){print(scripts.files[x]);try(suppressMessages(source(paste0("running_scripts/",scripts.files[x]))),silent=TRUE)})
a=lapply(out,class)
ind.error=grep("try-error",a)


for(i in 1:length(scripts.files))
{
    cat("====================\n")
    print(scripts.files[i])
    if(i%in%ind.error)
    {
        cat(out[[i]],"\n")
    }else{
        cat("all good\n\n")
    }
    cat("====================\n")
    
}

if(length(ind.error)>0)
{
  cat("\n\nerror found in the following test files:\n\n")
  for(i in ind.error)
  {
      cat(scripts.files[i],"\n")
    
  }
  cat("\n\n the best way forward is to source each faulty script and traceback() to get the line that broke the code\n")
}else{
  
  cat("\n\n NO ERROR found! Good luck on CRAN \n\n")
  
}

```

%Note: this pdf is a light version of all the tests. If you want more, you need to change additional.test=TRUE